version: 2

jobs:
  build:
    docker:
      - image: cimg/openjdk:17.0.1
        environment:
            DB_ROOT_USER: sa
            DB_URL: jdbc:h2:file:~/data/tribes
            DB_DRIVER: org.h2.Driver
            DB_PASS: password
            TZ: Europe/Prague

#          DB_ROOT_USER: user
#          DB_URL: jdbc:mysql://localhost/tribes?serverTimezone=UTC
#          DB_DRIVER: com.mysql.cj.jdbc.Driver

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}

      - run:
          name: Gradlew build
          command: |
            sudo chmod +x gradlew
            ./gradlew build

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

      # run tests!
      - run: gradle test
      - store_artifacts:
               path: build/reports/jacoco/test


